const StatusCodes = Object.freeze({
    AUTH_SUCCESS: 0,
    USER_NOT_FOUND: 1,
    INVALID_TOKEN_FOR_USERID: 2,
    AUTH_TOKEN_EXPIRED: 3,
    UNKNOWN_ERROR: 4,

    CHAT_ALREADY_EXISTS: 100,
    CHAT_CREATION_SUCCESSFUL: 101,

    CHAT_NOT_FOUND: 200,
    CHAT_WRONG_PASSWORD: 201,
    CHAT_ALREADY_JOINED: 202,
    CHAT_JOIN_SUCCESSFUL: 203,

    MESSAGE_RECEIVED: 300,

    SYNC_MESSAGES_SUCCESS: 400,
});

module.exports = { StatusCodes }